/* Generated by npm run env:gen — do not edit by hand */
window.__BUILDBET_SUPABASE = {"url":"https://wflwkxsqsyregnqbmctq.supabase.co","anonKey":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmbHdreHNxc3lyZWducWJtY3RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYxOTYwMDIsImV4cCI6MjA5MTc3MjAwMn0.__GHxd5BzCxpUaHU551m9hY110RK8A56Rhrs_TTb93k"};
